seed: 42
learning_rate: 5.0e-05
# num_train_epochs: 3
total_train_examples: 3200 # num_train_epochs will be determined to make the total number of examples near this value
per_device_train_batch_size: 1
per_device_eval_batch_size: 1
warmup_ratio: 0.1
weight_decay: 0.01
logging_strategy: steps
logging_steps: 100
eval_strategy: steps
eval_steps: 500
save_strategy: steps
save_steps: 500
save_total_limit: 2
load_best_model_at_end: true
metric_for_best_model: eval_loss
greater_is_better: false
gradient_accumulation_steps: 1
max_grad_norm: 1.0
bf16: true
fp16: false
report_to: tensorboard
remove_unused_columns: false
dataset_text_field: ""
dataset_kwargs:
  skip_prepare_dataset: true
dataset_num_proc: 4
label_names:
  - labels
